import os
import pytz

# INSTALLATION PATH
LUMIBOT_INSTALLATION_PATH = os.path.dirname(os.path.abspath(__file__))

# GLOBAL PARAMETERS
LUMIBOT_DEFAULT_TIMEZONE = "America/New_York"
LUMIBOT_DEFAULT_PYTZ = pytz.timezone(LUMIBOT_DEFAULT_TIMEZONE)

# CACHING CONFIGURATIONS
LUMIBOT_CACHE_PATH = os.path.join(LUMIBOT_INSTALLATION_PATH, "cache")
LUMIBOT_YAHOO_CACHE_PATH = os.path.join(LUMIBOT_CACHE_PATH, "yahoo")
